substitutions:
  name: ble-proxy-9630a8
  friendly_name: BLE Proxy 9630a8
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret ap_password

api:
  encryption:
    key: !secret api_encryption_key

logger:

ota:
  password: !secret ota_password