# based on 
#   https://devices.esphome.io/devices/ESP-12F-Relay-X4
#   https://esphome.io/components/sprinkler#single-controller-three-valves-single-pump


substitutions:
  hide_internal_switches: "false"  # for initial debugging

esphome:
  name: dripper
  friendly_name: Dripper

esp8266:
  board: esp12e

logger: # Enable logging

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret ap_password

captive_portal:

# specifics:

sprinkler:
  - id: dripper_ctrlr
    main_switch: "Dripper Sprinklers"
    auto_advance_switch: "Dripper Auto Advance"
    pump_start_pump_delay: 3s
    pump_stop_valve_delay: 3s
    valve_overlap: 3s
    valves:
      - valve_switch: "Valve 1"
        enable_switch: "Enable Valve 1"
        pump_switch_id: pump
        run_duration: 90s
        valve_switch_id: valve1
      - valve_switch: "Valve 2"
        enable_switch: "Enable Valve 2"
        pump_switch_id: pump
        run_duration: 90s
        valve_switch_id: valve2
      - valve_switch: "Valve 3"
        enable_switch: "Enable Valve 3"
        pump_switch_id: pump
        run_duration: 90s
        valve_switch_id: valve3

switch:
  - platform: gpio
    id: pump
    name: "[INTERNAL] Pump"
    pin: GPIO15
    internal: ${hide_internal_switches}

  - platform: gpio
    id: valve1
    name: "[INTERNAL] Valve 1"
    pin: GPIO14
    internal: ${hide_internal_switches}
  - platform: gpio
    id: valve2
    name: "[INTERNAL] Valve 2"
    pin: GPIO12
    internal: ${hide_internal_switches}
  - platform: gpio
    id: valve3
    name: "[INTERNAL] Valve 3"
    pin: GPIO13
    internal: ${hide_internal_switches}

# TODO: review usage of LED
light:
  - platform: status_led
    pin: GPIO5
    id: led

# interval:
#   - interval: 1000ms
#     then:
#       - light.turn_on: led
#       - delay: 200ms
#       - light.turn_off: led
