# based on https://devices.esphome.io/devices/ESP-12F-Relay-X4

esphome:
  name: dripper
  friendly_name: Dripper

esp8266:
  board: esp12e


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret ap_password

captive_portal:

# specifics:


output:
  - platform: gpio
    pin: GPIO5
    id: led

  - platform: gpio
    pin: GPIO15
    id: relay_1
  - platform: gpio
    pin: GPIO14
    id: relay_2
  - platform: gpio
    pin: GPIO12
    id: relay_3
  - platform: gpio
    pin: GPIO13
    id: relay_4

switch:
  - platform: output
    id: pump
    name: "Pump"
    output: relay_1
  - platform: output
    id: valve1
    name: "Valve 1"
    output: relay_2
  - platform: output
    id: valve2
    name: "Valve 2"
    output: relay_3
  - platform: output
    id: valve3
    name: "Valve 3"
    output: relay_4 
    
interval:
  - interval: 1000ms
    then:
      - output.turn_on: led
      - delay: 200ms
      - output.turn_off: led