esphome:
  name: "r-hub"
  friendly_name: R-Hub

esp32:
  board: m5stack-atom
  framework:
    # type: arduino
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret ap_password

captive_portal:

# enable BLE proxy
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true 

i2c:
  - sda: 26
    scl: 32

sensor:
    # CO2 sensor:
  - platform: scd4x
    update_interval: 5min
    co2:
      name: "CO2"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

  # diagnostics:
  - platform: wifi_signal
    name: WiFi Signal Strength
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    entity_category: "diagnostic"
